### ISSUE TITLE
New are avaliable new date updates 

### ISSUE THREAD

**Issue by blanchp** [owid/notebooks#5]
Hi,
I would be very interesting for me to analyze this democracy dataset, I need to have the more updated date as posible.
Are you going to update 2021 and 2022 info?

**Comment by bastianherre** [comment]
Hi!

Thank you for your interesting in our work and data!

Yes, we at Our World in Data aim to update our own data within a few weeks of the release of new data by the producers of democracy data.

Most producers already provide data for 2021, which you can all find [here](https://github.com/owid/notebooks/tree/main/BastianHerre/democracy). We will add the data for 2022 as it becomes available.

Please let me know if you have any follow-up or related questions!

**Comment by blanchp** [comment]
Hi, 
Sorry but the last year I see in "bmr_final.csv" is from 2020. In which dataset are you updating?

<img width="74" alt="shot" src="https://user-images.githubusercontent.com/122808472/214827327-6b865640-365d-49f9-a50c-dc24112b9379.png">

**Comment by blanchp** [comment]
The variable I want to analyse in particular is "regime_brm_owid" from brm_final.csv

**Comment by bastianherre** [comment]
Yes, the Boix et al. (BMR) dataset is one of the few datasets that only goes until 2020. We will update it once a new version becomes available. But we do not know when that will be.

Other datasets, such as Regimes of the World / Varieties of Democracy ([spreadsheet here](https://github.com/owid/notebooks/blob/main/BastianHerre/democracy/datasets/final/vdem_row_final.csv)) and the Lexical Index ([spreadsheet here](https://github.com/owid/notebooks/blob/main/BastianHerre/democracy/datasets/final/lied_final.csv)) have more recent data. Could these sources therefore be more helpful to you?

**Comment by blanchp** [comment]
That was exactly what I needed, thanks a lot for your help!

De: bastianherre ***@***.***>
Enviado el: viernes, 27 de enero de 2023 12:20
Para: owid/notebooks ***@***.***>
CC: Paula Blanch Romero ***@***.***>; Author ***@***.***>
Asunto: Re: [owid/notebooks] New are avaliable new date updates (Issue #5)

ATENCIÓN: Este correo electrónico se envió desde fuera de la organización. No haga clic en enlaces ni abra archivos adjuntos a menos que reconozca al remitente y sepa que el contenido es seguro.


Yes, the Boix et al. (BMR) dataset is one of the few datasets that only goes until 2020. We will update it once a new version becomes available. But we do not know when that will be.

Other datasets, such as Regimes of the World / Varieties of Democracy (spreadsheet here<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fowid%2Fnotebooks%2Fblob%2Fmain%2FBastianHerre%2Fdemocracy%2Fdatasets%2Ffinal%2Fvdem_row_final.csv&data=05%7C01%7Cpblanch%40accioncontraelhambre.org%7Cdf362e92ba6c491c1ac908db0058612a%7Cff105d4f039f444fbd6f0ed1e35daef4%7C0%7C0%7C638104151803339690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=76LZ56KFWJ4OgzdyhWZ9eVolWjFFeGViC5vo2FyuBoc%3D&reserved=0>) and the Lexical Index (spreadsheet here<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fowid%2Fnotebooks%2Fblob%2Fmain%2FBastianHerre%2Fdemocracy%2Fdatasets%2Ffinal%2Flied_final.csv&data=05%7C01%7Cpblanch%40accioncontraelhambre.org%7Cdf362e92ba6c491c1ac908db0058612a%7Cff105d4f039f444fbd6f0ed1e35daef4%7C0%7C0%7C638104151803339690%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z%2BU9%2Byce4yuIXWwrCyC5dEry7osLeQrMoUSidR%2FSnfk%3D&reserved=0>) have more recent data. Could these sources therefore be more helpful to you?

-
